# Generated by Django 3.1 on 2020-08-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='img',
            new_name='image',
        ),
    ]
